apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nba-elt-rest-api.fullname" . }}
  labels:
    {{- include "nba-elt-rest-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nba-elt-rest-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nba-elt-rest-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nba-elt-rest-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: IP
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: RDS_HOST
            - name: RDS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: RDS_USER
            - name: RDS_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: RDS_PW
            - name: RDS_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: RDS_DB
            - name: RDS_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: RDS_SCHEMA
            - name: ENV_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: ENV_TYPE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: API_KEY
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otelEndpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: OTEL_EXPORTER_OTLP_HEADERS
            - name: OTEL_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: OTEL_SERVICE_NAME
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
                  key: REDIS_URL
          volumes:
            - name: app-data
              emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
