apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nba-elt-rest-api.fullname" . }}-secrets
  labels:
    {{- include "nba-elt-rest-api.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  ENV_TYPE: {{ .Values.secrets.envType | b64enc | quote }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ .Values.secrets.otelHeaders | b64enc | quote }}
  OTEL_SERVICE_NAME: {{ .Values.secrets.otelServiceName | b64enc | quote }}
  RDS_HOST: {{ .Values.secrets.rdsHost | b64enc | quote }}
  RDS_USER: {{ .Values.secrets.rdsUser | b64enc | quote }}
  RDS_PW: {{ .Values.secrets.rdsPassword | b64enc | quote }}
  RDS_DB: {{ .Values.secrets.rdsDb | b64enc | quote }}
  RDS_SCHEMA: {{ .Values.secrets.rdsSchema | b64enc | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
