---
# Source: nba-elt-rest-api/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nba-elt-rest-api-prod
  labels:
    helm.sh/chart: nba-elt-rest-api-0.0.1
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: nba-elt-rest-api/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nba-elt-rest-api-prod-secrets
  labels:
    helm.sh/chart: nba-elt-rest-api-0.0.1
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  API_KEY: ""
  ENV_TYPE: "cHJvZHVjdGlvbg=="
  OTEL_EXPORTER_OTLP_HEADERS: ""
  OTEL_SERVICE_NAME: "bmJhLWVsdC1yZXN0LWFwaS1wcm9k"
  RDS_HOST: ""
  RDS_USER: ""
  RDS_PW: ""
  RDS_DB: "bmJhX3Byb2Q="
  RDS_SCHEMA: "cHJvZF9zY2hlbWE="
  REDIS_URL: ""
---
# Source: nba-elt-rest-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nba-elt-rest-api-prod
  labels:
    helm.sh/chart: nba-elt-rest-api-0.0.1
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
---
# Source: nba-elt-rest-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-elt-rest-api-prod
  labels:
    helm.sh/chart: nba-elt-rest-api-0.0.1
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nba-elt-rest-api
      app.kubernetes.io/instance: nba-elt-rest-api-prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nba-elt-rest-api
        app.kubernetes.io/instance: nba-elt-rest-api-prod
    spec:
      serviceAccountName: nba-elt-rest-api-prod
      securityContext:
        {}
      containers:
        - name: nba-elt-rest-api
          securityContext:
            {}
          image: "your-registry/nba_elt_rest_api:v1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 2000m
              memory: 2Gi
          env:
            - name: IP
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: RDS_HOST
            - name: RDS_USER
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: RDS_USER
            - name: RDS_PW
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: RDS_PW
            - name: RDS_DB
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: RDS_DB
            - name: RDS_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: RDS_SCHEMA
            - name: ENV_TYPE
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: ENV_TYPE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: API_KEY
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "https://api.honeycomb.io"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: OTEL_EXPORTER_OTLP_HEADERS
            - name: OTEL_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: OTEL_SERVICE_NAME
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: nba-elt-rest-api-prod-secrets
                  key: REDIS_URL
          volumes:
            - name: app-data
              emptyDir: {}
---
# Source: nba-elt-rest-api/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nba-elt-rest-api-prod
  labels:
    helm.sh/chart: nba-elt-rest-api-0.0.1
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nba-elt-rest-api-prod
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
# Source: nba-elt-rest-api/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nba-elt-rest-api-prod
  labels:
    helm.sh/chart: nba-elt-rest-api-0.0.1
    app.kubernetes.io/name: nba-elt-rest-api
    app.kubernetes.io/instance: nba-elt-rest-api-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "api.jyablonski.dev"
      secretName: nba-api-tls
  rules:
    - host: "api.jyablonski.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nba-elt-rest-api-prod
                port:
                  number: 8080
